-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin
(
    id_admin serial NOT NULL,
    nama_admin character varying(30) COLLATE pg_catalog."default",
    nomor_telepon bigint,
    username character varying(30) COLLATE pg_catalog."default",
    password character varying(30) COLLATE pg_catalog."default",
    provinsi character varying(30) COLLATE pg_catalog."default",
    kabupaten character varying(30) COLLATE pg_catalog."default",
    kecamatan character varying(30) COLLATE pg_catalog."default",
    jalan character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT admin_pkey PRIMARY KEY (id_admin)
);

CREATE TABLE IF NOT EXISTS public.bahan_mentah
(
    id_bahan_mentah serial NOT NULL,
    nama_bahan_mentah character varying(30) COLLATE pg_catalog."default",
    kuantitas_bahan_mentah integer,
    id_jenis_bahan_mentah integer,
    id_admin integer,
    id_pelatih integer,
    id_satuan_bahan_mentah integer,
    CONSTRAINT bahan_mentah_pkey PRIMARY KEY (id_bahan_mentah)
);

CREATE TABLE IF NOT EXISTS public.jenis_bahan_mentah
(
    id_jenis_bahan_mentah serial NOT NULL,
    nama_jenis_bahan_mentah character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT jenis_bahan_mentah_pkey PRIMARY KEY (id_jenis_bahan_mentah)
);

CREATE TABLE IF NOT EXISTS public.jenis_kelas
(
    id_jenis_kelas serial NOT NULL,
    deskripsi text COLLATE pg_catalog."default",
    nama_jenis_kelas character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT jenis_kelas_pkey PRIMARY KEY (id_jenis_kelas)
);

CREATE TABLE IF NOT EXISTS public.kelas
(
    id_kelas serial NOT NULL,
    nama_kelas character varying(30) COLLATE pg_catalog."default",
    id_pelatih integer,
    id_admin integer,
    id_jenis_kelas integer,
    waktu character varying(20) COLLATE pg_catalog."default",
    hari character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT kelas_pkey PRIMARY KEY (id_kelas)
);

CREATE TABLE IF NOT EXISTS public.pelatih
(
    id_pelatih serial NOT NULL,
    nama_pelatih character varying(30) COLLATE pg_catalog."default",
    kontak_pelatih bigint,
    username character varying(30) COLLATE pg_catalog."default",
    password character varying(30) COLLATE pg_catalog."default",
    provinsi character varying(30) COLLATE pg_catalog."default",
    kabupaten character varying(30) COLLATE pg_catalog."default",
    kecamatan character varying(30) COLLATE pg_catalog."default",
    jalan character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT pelatih_pkey PRIMARY KEY (id_pelatih)
);

CREATE TABLE IF NOT EXISTS public.satuan_bahan_mentah
(
    id_satuan_bahan_mentah serial NOT NULL,
    nama_satuan_bahan_mentah character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT satuan_bahan_mentah_pkey PRIMARY KEY (id_satuan_bahan_mentah)
);

CREATE TABLE IF NOT EXISTS public.sertifikat
(
    id_sertifikat serial NOT NULL,
    deskripsi text COLLATE pg_catalog."default",
    nama_sertifikat character varying(30) COLLATE pg_catalog."default",
    id_siswa integer,
    CONSTRAINT sertifikat_pkey PRIMARY KEY (id_sertifikat)
);

CREATE TABLE IF NOT EXISTS public.siswa
(
    id_siswa serial NOT NULL,
    nama_siswa character varying(30) COLLATE pg_catalog."default",
    umur_siswa integer,
    gender_siswa character varying(30) COLLATE pg_catalog."default",
    username character varying(30) COLLATE pg_catalog."default",
    password character varying(30) COLLATE pg_catalog."default",
    provinsi character varying(30) COLLATE pg_catalog."default",
    kabupaten character varying(30) COLLATE pg_catalog."default",
    kecamatan character varying(30) COLLATE pg_catalog."default",
    jalan character varying(50) COLLATE pg_catalog."default",
    id_kelas integer,
    CONSTRAINT siswa_pkey PRIMARY KEY (id_siswa)
);

ALTER TABLE IF EXISTS public.bahan_mentah
    ADD CONSTRAINT fk_admin_bahan_mentah FOREIGN KEY (id_admin)
    REFERENCES public.admin (id_admin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bahan_mentah
    ADD CONSTRAINT fk_jenis_bahan_mentah_bahan_mentah FOREIGN KEY (id_jenis_bahan_mentah)
    REFERENCES public.jenis_bahan_mentah (id_jenis_bahan_mentah) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bahan_mentah
    ADD CONSTRAINT fk_pelatih_bahan_mentah FOREIGN KEY (id_pelatih)
    REFERENCES public.pelatih (id_pelatih) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bahan_mentah
    ADD CONSTRAINT fk_satuan_bahan_mentah FOREIGN KEY (id_satuan_bahan_mentah)
    REFERENCES public.satuan_bahan_mentah (id_satuan_bahan_mentah) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.kelas
    ADD CONSTRAINT fk_admin_kelas FOREIGN KEY (id_admin)
    REFERENCES public.admin (id_admin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.kelas
    ADD CONSTRAINT fk_jenis_kelas_kelas FOREIGN KEY (id_jenis_kelas)
    REFERENCES public.jenis_kelas (id_jenis_kelas) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.kelas
    ADD CONSTRAINT fk_pelatih_kelas FOREIGN KEY (id_pelatih)
    REFERENCES public.pelatih (id_pelatih) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sertifikat
    ADD CONSTRAINT fk_siswa_sertifikat FOREIGN KEY (id_siswa)
    REFERENCES public.siswa (id_siswa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.siswa
    ADD CONSTRAINT fk_kelas_siswa FOREIGN KEY (id_kelas)
    REFERENCES public.kelas (id_kelas) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;